kind: Secret
apiVersion: v1
metadata:
  name: laravel-env-secrets
  namespace: laravel
data:
  APP_KEY: ''
  VITE_REVERB_APP_KEY: ''
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: build-laravel-app
  namespace: laravel
data:
  WebHookSecretKey: ''
type: Opaque
